export const descriptions = [
    'a dark, damp room with flickering torches casting long shadows, the air thick with the scent of mold. The oppressive silence is broken only by the occasional drip of water echoing in the distance.',
    'a brightly lit room with polished marble floors that reflect the golden glow of grand chandeliers, the walls adorned with opulent paintings. The air is warm and still, with a sense of grandeur lingering from a forgotten era.',
    'a room overflowing with treasure chests brimming with glittering jewels, gold coins scattered across the floor like stars in the night sky. The sight is mesmerizing, but a feeling of unease gnaws at you, as if something is watching from the shadows.',
    'a narrow corridor with eerie whispers that seem to come from the walls themselves, a cold draft chilling your spine. Each step echoes unnervingly, making it hard to tell whether you are alone or not.',
    'a grand hall with towering stone pillars, a high ceiling lost in darkness, and ancient tapestries depicting long-forgotten wars. The air is thick with the weight of history, and the silence feels almost sacred.',
    'a quiet library with towering bookshelves, their contents covered in dust, the scent of ancient paper hanging in the air. A soft rustling sound comes from somewhere deep within, as though the books themselves are restless.',
    'a small, cozy room bathed in the warm glow of a crackling fireplace, with plush chairs inviting you to rest. The gentle crackle of the fire is soothing, and for a moment, it feels as if all your worries could melt away.',
    'a room cluttered with bubbling cauldrons and shelves lined with strange, glowing potions, the scent of herbs and sulfur thick in the air. Strange symbols glow faintly on the walls, and the air hums with the energy of hidden magic.',
    'a room with ancient runes carved into the stone walls, glowing faintly with an otherworldly light, the atmosphere charged with mysterious energy. The runes pulse softly, as though alive with secrets long forgotten.',
    'a vast, echoing cavern with a crystal-clear underground lake, the water shimmering with an ethereal glow. The cavern’s ceiling disappears into darkness, and the stillness of the water creates an eerie sense of calm.',
    'a room where the walls are entirely made of mirrors, reflecting countless versions of yourself in dizzying patterns. The reflections seem slightly delayed, as if the mirror-world is just out of sync with your reality.',
    'a cramped chamber filled with cobwebs, the scuttling of unseen creatures echoing in the dark corners. The air smells of decay, and each step you take stirs up a thick layer of dust.',
    'a peaceful garden-like room with vines hanging from the ceiling and the soft sound of trickling water from a stone fountain. The air smells of fresh earth, and the faint glow of bioluminescent flowers provides a gentle, soothing light.',
    'a grand banquet hall with a long table set for a feast, though no one is in sight and the food appears untouched. The plates gleam under candlelight, but the eerie silence makes the scene feel like a frozen moment in time.',
    'a cold stone crypt with rows of sarcophagi, the air thick with dust and the weight of ages long past. The walls are lined with forgotten names, and the atmosphere is heavy with the presence of the dead.',
    'a tower room with a view of the distant horizon through a single, narrow window, the wind howling outside. The stone walls feel cold and unwelcoming, as if the tower itself is waiting for something long overdue.',
    'a forge-like chamber, the heat intense, with the sound of metal striking metal echoing through the room. Sparks fly in the dim light, and the air is thick with the smell of molten steel and sweat.',
    'a small room where clocks of all sizes tick relentlessly, their hands moving in odd, irregular patterns. Time feels distorted here, as if the very concept of it is coming undone.',
    'a laboratory filled with glass vials and strange apparatus, the scent of chemicals pungent in the air. The bubbling liquids and crackling energy suggest that dangerous experiments are taking place here, perhaps long abandoned.',
    'a music room with a grand piano, though no one plays, the keys sometimes striking themselves in eerie, discordant notes. The haunting melody lingers in the air, filling the room with a sense of melancholy.',
    'a damp cellar with barrels stacked high, the scent of wine and something far less pleasant in the air. The floor is slick with moisture, and you can hear the faint sound of something shifting in the darkness.',
    'a grand, domed observatory with a massive telescope aimed at the stars, though the sky outside seems unusually dark. Dust has settled over everything, and the silence is broken only by the faint creak of the telescope swiveling, though no one touches it.',
    'a room with an altar at the center, covered in strange, glowing symbols and lit by an unknown source. The air hums with power, and the atmosphere is thick with a sense of impending ritual or sacrifice.',
    'a dimly lit cave, the sound of dripping water echoing, with glittering gemstones embedded in the rocky walls. The gems catch the light, casting faint, colorful glows, though the darkness seems to swallow sound and movement alike.',
    'a room where the floor is made of transparent glass, revealing a deep abyss beneath your feet, filled with shifting shadows. The sensation of vertigo makes each step feel dangerous, as if the glass could shatter at any moment.',
    'a dilapidated ballroom, its once-grand features decayed, chandeliers hanging precariously and tattered curtains swaying. The faint sound of forgotten music lingers in the air, though the room has long since fallen into ruin.',
    'a room filled with strange mechanical contraptions, gears turning endlessly with no apparent purpose. The rhythmic clanking creates an unsettling soundtrack, as if the machines have been operating for centuries without a soul in sight.',
    'a peaceful sanctuary with soft, glowing light and an overwhelming sense of calm, as though time has slowed within these walls. The gentle hum of tranquility is almost otherworldly, as if this place is untouched by the chaos outside.',
    'a vast underground cavern lit by bioluminescent fungi, their soft glow casting eerie shadows on the stone walls. The air is cool and damp, and the faint luminescence creates a dreamlike atmosphere, as if the cavern belongs to another world.',
    'a small, dusty attic where old wooden beams creak underfoot. Faint light filters in through a cracked window, illuminating cobweb-covered trunks and forgotten relics.',
    'a wide-open desert chamber, the air dry and scorching. Sand swirls across the floor, and the distant rumble hints at a brewing sandstorm.',
    'a vast cathedral-like hall, its ceiling lost in darkness. The stained glass windows glow faintly with an otherworldly light.',
    'a cavern of glimmering crystals, their light bouncing off the walls in a kaleidoscope of colors. The air hums with a strange, melodic energy.',
    'a lush jungle room where vines hang from every surface, and the sound of distant animal calls fills the air. The scent of damp earth and exotic plants is overwhelming.',
    'a grand amphitheater, its stone seats empty, but whispers of long-forgotten crowds echo in the distance. The center stage seems frozen in time, waiting for a performer.',
    'a room submerged in water up to your knees, ripples forming with every step. Strange aquatic plants glow beneath the surface, illuminating the path.',
    'a narrow passage with walls that seem to close in around you, the air heavy and thick. Shadows flicker, though no torches are visible.',
    'a decrepit church where broken pews lie scattered and the altar is covered in dust. Moonlight streams through shattered stained glass windows, casting eerie patterns on the floor.',
    'a room where snow falls gently from the ceiling, covering the floor in a pristine white layer. The air is freezing, and your breath fogs in front of you.',
    'a long-abandoned nursery with crumbling cribs and faded toys scattered on the floor. The faint sound of a lullaby can be heard, though no source is visible.',
    'a hall of mirrors, each reflecting distorted versions of yourself. Some reflections move in ways they shouldn’t, as though they have a life of their own.',
    'a room filled with oversized mushrooms and strange glowing plants, the atmosphere humid and the air thick with spores. It feels like stepping into another world.',
    'a chamber where everything is made of bone—walls, floors, and even the furniture. The bones creak ominously with each movement, as if they might come to life.',
    'a room with a gaping hole in the center, where an eerie blue light shines from the depths below. The edges of the pit are jagged, and the faint sound of wind echoes up.',
    'a grand library, larger than any you’ve ever seen, with books towering high above you. The scent of ancient parchment fills the air, and the silence is almost deafening.',
    'a stone dungeon where the walls are damp and the floor slick with grime. The faint sound of chains rattling echoes in the distance.',
    'a golden throne room, though the throne itself is empty and covered in dust. The air is thick with the sense of something long-forgotten.',
    'a room filled with swirling mist that obscures the floor and walls, making it impossible to tell how large the space is. The mist seems to whisper as it moves.',
    'a moonlit garden with tall hedges and statues of forgotten gods. The flowers glow faintly under the silver light, and the air is cool and crisp.',
    'a room where time seems to stand still, with objects frozen mid-fall, and dust hanging motionless in the air. It’s as though the world has paused just for this moment.',
    'a clock tower chamber, the sound of ticking echoing loudly in the confined space. Gears larger than you turn slowly, their purpose unknowable.',
    'a room entirely carved from ice, every surface glinting in the dim light. The cold is biting, and the sound of cracking ice can be heard all around.',
    'a grand ballroom with a polished floor, though no dancers remain. The faint echoes of music linger, as though the last dance ended only moments ago.',
    'a room filled with forgotten relics, ancient statues, and broken pottery. The air is thick with the scent of dust and history, as if time itself has settled here.',
    'a room where every wall is a different color, vibrant and disorienting. The floor shifts slightly beneath your feet, as though alive.',
    'a hollow cave where the walls are covered in ancient carvings and symbols. The air is cool, and the carvings seem to tell a story lost to time.',
    'a dimly lit tavern where the tables are empty, yet the fire in the hearth still burns brightly. The smell of old ale and charred wood lingers in the air.',
    'a circular room with a domed ceiling painted like the night sky. The stars seem to twinkle, and constellations shift ever so slightly as you watch.',
    'a ruined fortress where shattered walls crumble and the ground is littered with debris. The wind howls through broken windows, carrying the scent of decay.',
    'a cave with walls lined by bioluminescent fungi, casting a soft blue glow. The sound of water dripping echoes through the stillness, and the air smells faintly of damp earth.',
    'a twisting, spiral staircase that seems to go both up and down at the same time, with no end in sight. The air is heavy with the sense of being trapped in an endless loop.',
    'a dark, endless hallway where doors line the walls, though none of them open. The sound of your footsteps is the only thing that breaks the silence.',
    'a room where the ceiling is low and oppressive, covered in roots and vines that hang like twisted fingers. The air is damp, and the ground squelches beneath your feet.'

];


export const impassableDescriptions = [
    'a room blocked by a massive cave-in, debris and rocks piled high, making passage impossible. The air is thick with dust, and the sound of distant settling stones echoes through the stillness.',
    'a room with a yawning bottomless pit, the black abyss below swallowing all light and sound. Any attempt to cross would lead to a fatal plunge into the unknown.',
    'a room filled with a thick, deadly gas that hangs like a fog, suffocating and impossible to pass through. The stench of rot and decay fills the air, making even breathing from a distance dangerous.',
    'a room with walls covered in razor-sharp spikes, closing in from all sides, threatening instant death. The spikes glisten with a sinister gleam, leaving no hope of safe passage.',
    'a room engulfed in a raging fire, flames licking the walls and ceiling, the heat unbearable from even a distance. The crackling of the fire is deafening, and the air itself seems to burn.',
    'a room where the ceiling is slowly collapsing, massive stones falling unpredictably, making movement dangerous. Each crash of stone against stone reverberates like thunder, leaving no safe haven.',
    'a room submerged in dark, murky water, the surface rippling but no safe way to pass visible. The water is cold and foreboding, hiding whatever dangers lurk beneath its opaque surface.',
    'a chamber filled with rapidly shifting sand, sinking deeper the longer you stand, impossible to escape by foot. The sand swirls and shifts, as though alive, dragging anything caught in it to certain doom.',
    'a room frozen solid, the walls and floor slick with ice, the temperature so low that the air stings your skin. Frost clings to every surface, and even the slightest movement would send you sliding into the icy unknown.',
    'a room where the floor is covered with swarming insects, their chittering filling the air, making passage impossible. The floor seems alive with the crawling, writhing mass, their bites venomous and deadly.',
    'a room where the walls are closing in, the grinding of stone filling the air, leaving no space to pass. The air is thick with the smell of crushed stone, and the grinding noise grows louder with every second.',
    'a room completely filled with thick, thorny vines, their barbs sharp enough to tear through flesh. The vines pulse and twist, as though they’re waiting to ensnare any who attempt to cross.',
    'a room with a whirlpool of black water spinning in the center, the pull too strong to resist. The water churns violently, and the air is filled with the roar of its deadly current.',
    'a room with a giant boulder rolling back and forth, crushing anything in its path with relentless force. The ground shakes with each pass of the boulder, leaving no time to make it across safely.',
    'a room where gravity is distorted, pulling you toward the ceiling or walls, disorienting and deadly to traverse. The very laws of physics seem twisted here, making every step a dangerous gamble.',
    'a room filled with glowing, unstable crystals, crackling with dangerous energy that sparks across the floor. The crystals hum ominously, their light flickering like a warning of the danger they pose.',
    'a room where a swarm of spectral beings flicker in and out of existence, their touch lethal to the living. Their ghostly whispers fill the air, and the temperature drops drastically in their presence.',
    'a room flooded with poisonous fumes, the air unbreathable, with no way to clear the suffocating gas. The fumes coil like living things, and even the faintest whiff would be enough to paralyze.',
    'a room where the floor is nothing but jagged, broken glass, impassable without severe injury. Each step would mean slicing through flesh, with no hope of avoiding the shards.',
    'a room filled with molten lava, bubbling and splashing onto the stone, creating an impenetrable barrier. The heat radiates outward in waves, and the ground trembles as the molten rock churns.',
    'a room where the floor has completely collapsed into a gaping chasm, the jagged edges of stone warning against any attempt to jump. The distant sound of dripping water echoes from the unseen depths below.',
    'a room filled with webs thicker than ropes, stretching from wall to wall, impossible to cut through. The air is stifling, and the faint scuttle of unseen creatures adds to the unease.',
    'a room where lightning arcs continuously from wall to wall, crackling with deadly energy. The air is charged, and every step toward the center is met with an unbearable, buzzing heat.',
    'a room sealed off by an enormous iron door, rusted and ancient, with no visible means of opening. The faint groan of metal can be heard, but the door remains unyielding and immovable.',
    'a room where the ground is completely covered in quicksand, swirling and shifting as though alive. Any attempt to cross would see you swallowed up in moments, with no hope of rescue.',
    'a room plunged into total darkness, so complete that even sound seems to vanish into the void. There is no telling what lies within, but every instinct warns you not to venture further.',
    'a room where the walls are lined with burning oil, the flames roaring and crackling, filling the air with acrid smoke. The fire consumes all, leaving no safe path forward.',
    'a room with an electrified floor, each step sending sparks of energy jolting upwards. The metallic scent of burning air and the hum of electricity make it impossible to proceed.',
    'a room encased in solid crystal, its facets reflecting light in dazzling patterns but trapping everything inside. The walls are cold and smooth, unbreakable and alien in their perfection.',
    'a room where the ceiling is hung with stalactites, each one dripping with an acidic substance that hisses upon contact with the ground. The liquid pools, eating away at the stone, leaving no safe passage.',
    'a room where massive chains dangle from the ceiling, swinging unpredictably with crushing force. Each heavy link thunders against the ground, threatening to flatten anything in its path.',
    'a room filled with thick, glowing mist that clings to everything, slowly draining the life from whatever it touches. The very air feels oppressive, and the mist pulses as if alive with intent.',
    'a room where the floor is composed of sharp, uneven stone, the gaps between filled with deep, black voids. One wrong step would send you plummeting into the abyss below.',
    'a room where a violent storm rages, the wind howling and tearing at the walls. Lightning crashes down from the ceiling, and the rain falls like needles, cutting into everything it touches.',
    'a room where the walls are constantly shifting, their stone surfaces grinding and reshaping with a deafening roar. There is no way to predict when they will crush the space entirely.',
    'a room where an enormous serpent coils in the center, its eyes glowing with malice. The air is thick with venom, and the creatures presence alone makes the room impassable.',
    'a room completely frozen over, where even the air seems to solidify and every breath crystallizes in front of you. The icy wind bites at exposed skin, leaving frostbite in mere seconds.',
    'a room where the ground is littered with shattered bones, and spectral figures patrol silently. Their empty eyes pass over you without recognition, but their presence is unmistakably hostile.',
    'a room engulfed by a blizzard, the snow swirling violently, obscuring everything in a freezing white haze. The wind howls like a beast, and the temperature plummets to lethal levels.',
    'a room where the walls are made of seething, molten metal, glowing bright orange and radiating unbearable heat. Even approaching the entrance feels like stepping into a furnace, making it impossible to advance.',
    'a room that seems to loop endlessly, every doorway leading back to the same spot, trapping you in a maddening cycle. The walls shift and twist, as though the very space itself is alive and intent on keeping you inside.',
    'a room with a colossal clock mechanism, its gears spinning violently, crushing anything that comes too close. The grinding of metal on metal fills the space, leaving no room for error or passage.',
    'a room filled with venomous plants, their thorny vines thrashing as if with a mind of their own. Each one is ready to strike, and the air is thick with the sweet scent of their deadly poison.',
    'a room where strange, otherworldly voices echo constantly, growing louder the closer you approach. The sound seems to invade your mind, making it impossible to think or move forward.',
    'a room where time itself seems frozen, everything within suspended in a perfect stillness, including the deadly traps just waiting to resume their lethal work. The moment you step inside, time will continue—ending in certain death.',
    'a room where an eerie, blue glow illuminates the skeletal remains of those who tried to cross before. The bones are piled high, and the stillness of the room is both suffocating and foreboding.',
    'a room where the floor is a labyrinth of razor-thin wire, nearly invisible to the eye but sharp enough to sever anything that touches it. The slightest misstep would slice through flesh and bone without mercy.',
    'a room filled with clouds of ash and soot, the remnants of a fierce fire that still smolders in places. The ground is unstable, crumbling underfoot, and the air is thick with choking dust.',
    'a room where the ceiling drips with molten metal, the drops sizzling as they hit the ground. The heat is unbearable, and the steady drip makes it impossible to find safe passage forward.',
    'a room submerged entirely underwater, the surface just inches above your head. The murky water is cold and foreboding, and there is no way to breathe or navigate the depths safely.'


];
